name: Check Build

env:
  DRAGONFLY_PATH: "${{github.workspace}}/build-opt/dragonfly"
  
on: 
  schedule:
    - cron: '0 7 */3 * *'
  workflow_dispatch:
      
jobs:
  build-n-test:
    runs-on: ghcr.io/romange/ubuntu-dev:20
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Creating build
        run: |
          sudo apt-get install -y lsb-release ninja-build libunwind-dev libboost-fiber-dev libssl-dev autoconf-archive libtool cmake g++
          ./helio/blaze.sh
          cd build-opt && ninja dragonfly
      - name: Run PyTests
        run: |
          echo "Current commit is ${{github.sha}}"
          chmod +x $DRAGONFLY_PATH
          cd ${{ github.workspace }}/tests
          pip install -r dragonfly/requirements.txt
          pytest -xv dragonfly
      - name: Send notification on failure
        if: failure()
        run: |
          curl -s \
            -X POST \
            -H 'Content-Type: application/json' \
            '${{ secrets.GSPACES_BOT_DF_BUILD }}' \
            -d '{"text": "Unforunately the tests of dragonfly build are not passed :( \nThe commit is ${{github.sha}}	"}'
