# These tests are disabled until Dragonfly works well with BullMQ.
name: bullmq-tests
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    timeout-minutes: 60
    container:
      image: ghcr.io/romange/alpine-dev:latest
      options: --security-opt seccomp=unconfined
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - name: Install NodeJs
        run: |
          apk add --no-cache nodejs npm yarn
          node --version
          npm --version
          yarn --version
          mkdir -p $GITHUB_WORKSPACE/build
      - name: Configure/Build
        run: |
          cd $GITHUB_WORKSPACE/build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja dragonfly
          ./dragonfly --alsologtostderr &

      - name: Clone and build BullMQ
        run: |
          git clone https://github.com/taskforcesh/bullmq.git
          cd bullmq
          pwd
          yarn install --ignore-engines --frozen-lockfile --non-interactive
          yarn build
      - name: Test BullMQ
        run: |
          cd $GITHUB_WORKSPACE/bullmq
          # yarn test -i -g "should process delayed jobs with several workers respecting delay"
