name: Regression Tests

env:
  BUILD_TYPE: Debug

on:
  schedule:
    - cron: '0 7 */3 * *'
  workflow_dispatch:

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test of these containers
        container: ["ubuntu-dev:20"]

    container:
      image: ghcr.io/romange/${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure & Build
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cd ${{github.workspace}}/build  && ninja dragonfly

      - name: Run PyTests
        run: |
          cd ${{ github.workspace }}/tests
          echo "Current commit is ${{github.sha}}"
          pip install -r dragonfly/requirements.txt
          export DRAGONFLY_PATH="${{github.workspace}}/build/dragonfly" # used by PyTests

          pytest -xv dragonfly

      - name: Send notification on failure
        if: failure()
        run: |
          curl -s \
            -X POST \
            -H 'Content-Type: application/json' \
            '${{ secrets.GSPACES_BOT_DF_BUILD }}' \
            -d '{"text": "Unforunately the tests of dragonfly build are not passed :( \n The commit is ${{github.sha}}	"}'
