name: Regression Tests

on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:




jobs:
  build-n-test:
    strategy:
      matrix:
        # Test of these containers
        container: ["ubuntu-dev:20"]
        build-type: [Debug, Release]
        runner: [ubuntu-latest, [self-hosted, linux, ARM64]]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 45

    container:
      image: ghcr.io/romange/${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Print cpu info
        run:  cat /proc/cpuinfo

      - name: Configure & Build
        run: |
          apt update && apt install -y pip jq
          cmake -B ${GITHUB_WORKSPACE}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -GNinja \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

          cd ${GITHUB_WORKSPACE}/build  && ninja dragonfly
          pwd
          ls -l ..

      - name: Run PyTests
        timeout-minutes: 20
        run: |
          ls -l ${GITHUB_WORKSPACE}/
          cd ${GITHUB_WORKSPACE}/tests
          echo "Current commit is ${{github.sha}}"
          pip install -r dragonfly/requirements.txt
          export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/build/dragonfly" # used by PyTests
          export UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 # to crash on errors

          pytest --json-report --json-report-file=report.json -svr dragonfly --ignore=dragonfly/replication_test.py --ignore=dragonfly/tls_replication_test.py

      - name: Run PyTests replication test
        if: ${{ matrix.runner  == 'ubuntu-latest' }}
        timeout-minutes: 20
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/build/dragonfly" # used by PyTests

          pytest --json-report --json-report-file=rep1_report.json -sv dragonfly/replication_test.py --df alsologtostderr --df enable_multi_shard_sync=true
          pytest --json-report --json-report-file=rep2_report.json -sv dragonfly/replication_test.py --df alsologtostderr --df enable_multi_shard_sync=false

      - name: Run PyTests replication test with tls
        if: ${{ matrix.runner  == 'ubuntu-latest' }}
        timeout-minutes: 20
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/build/dragonfly" # used by PyTests

          # We first need to generate the tls certificates to be used by the server

          # Step 1
          # Generate CA (certificate authority) key and self-signed certificate
          # In production, CA should be generated by a third party authority
          # Expires in one day and is not encrtypted (-nodes)
          # X.509 format for the key
          openssl req -x509 -newkey rsa:4096 -days 1 -nodes -keyout ca-key.pem -out ca-cert.pem -subj "/C=GR/ST=SKG/L=Thessaloniki/O=KK/OU=AcmeStudios/CN=Gr/emailAddress=acme@gmail.com"
          # Self sign the certificate
          openssl x509 -in ca-cert.pem -noout -text

          # Step 2
          # Generate Dragonfly's private key and certificate signing request (CSR)
          openssl req -newkey rsa:4096 -nodes -keyout df-key.pem -out df-req.pem -subj "/C=GR/ST=SKG/L=Thessaloniki/O=KK/OU=Comp/CN=Gr/emailAddress=does_not_exist@gmail.com"

          # Step 3
          # Use CA's private key to sign dragonfly's CSR and get back the signed certificate
          openssl x509 -req -in df-req.pem -days 1 -CA ca-cert.pem -CAkey ca-key.pem -CAcreateserial -out df-cert.pem -extfile df-ext.cnf

          # Start the test
          pytest --json-report --json-report-file=rep1_report.json -sv dragonfly/tls_replication_test.py --df alsologtostderr

      - name: Send notification on failure
        if: failure()
        run: |
          get_failed_tests() {
            local report_file=$1
            echo $(jq -r '.tests[] | select(.outcome == "failed") | .nodeid' "$report_file")
          }
          cd ${GITHUB_WORKSPACE}/tests
          failed_tests=""
          # The order in of if is important, and expected to be the oposite order of the pytest run.
          # As github runner will not run the next step if the pytest failed, we start from the last
          # report file and if exist we get the failed test from the pytest run, if there are any.
          if [ -f rep2_report.json ]; then
            failed_tests=$(get_failed_tests rep2_report.json)
          elif [ -f rep1_report.json ]; then
            failed_tests=$(get_failed_tests rep1_report.json)
          elif [ -f report.json ]; then
            failed_tests=$(get_failed_tests report.json)
          fi

          job_link="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          message="Regression tests failed.\\n The commit is: ${{github.sha}}.\\n $failed_tests \\n Job Link: ${job_link}\\n"

          curl -s \
            -X POST \
            -H 'Content-Type: application/json' \
            '${{ secrets.GSPACES_BOT_DF_BUILD }}' \
            -d '{"text": "'"${message}"'"}'
